### ISSUE TITLE
Spotify Dummy Screen

### ISSUE THREAD

**Issue by sparrow007** [Marvel999/FamousComposeBook#10]
### Home Screen Page

- Copy Home screen with dummy data
- Add the screenShots after submitting the PR
Figma Link:- https://www.figma.com/file/8Ox88S51XhIh0F19bYoZov/SpotifyRedesignChallenger-(1)?node-id=88%3A3686

**Comment by Marvel999** [comment]
https://github.com/Marvel999/FamousComposeBook/pull/14
